CREATE TABLE AUTHOR_TABLE OF AUTHOR_TYPE( 
CONSTRAINT PK_AUTHOR_TABLE PRIMARY KEY (AUTHOR_ID));

CREATE TABLE MEMBER_TABLE OF MEMBER_TYPE( 
CONSTRAINT PK_MEMBER_TABLE PRIMARY KEY (MEMBER_ID));

CREATE TABLE LOANS_TABLE OF loans_type
(copy_ref NOT NULL,
CONSTRAINT PK_LOANS_TABLE PRIMARY KEY(loan_id));

CREATE TABLE COPY_TABLE OF copy_type
(CONSTRAINT PK_COPY_TABLE PRIMARY KEY
(copy_id)); 


CREATE TABLE BOOKS_TABLE OF book_type
(CONSTRAINT PK_BOOKS_TABLE PRIMARY KEY
(isbn))
NESTED TABLE c_list STORE AS copy_l;

